name: JFrog Security Demo App Builder

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          #JFROG_XRAY_URL: ${{ secrets.JF_URL }}/xray
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: jf rt ping
        run: |
          jf rt ping
          
      - name: Docker login to Artifactory
        run: |
          echo ${{ secrets.JF_PASSWORD }} | docker login https://${{ vars.JF_URL }}/ -u ${{ secrets.JF_USER }} --password-stdin

      # - name: Authenticate Docker
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.JF_URL }}
      #     username: ${{ secrets.JF_USER }}
      #     password: ${{ secrets.JF_PASSWORD }}

      - name: Pull base image from Artifactory
        run: |
          jf docker pull ${{ vars.JF_URL }}/gartner-docker/jfrog/demo-security:latest

      - name: Build Docker image
        run: |
          jf docker build -t productdemo.jfrog.io/gartner-docker/jfrog/npm-demo:${{ github.run_number }} .
    
      - name: Push Docker image to Artifactory
        run: |
          jf docker push productdemo.jfrog.io/gartner-docker/jfrog/npm-demo:${{ github.run_number }}
      
      - name: Collect build info and scan
        run: |
          jf rt build-collect-env "JFrog Security Demo App Builder" ${{ github.run_number }}
          jf rt build-add-git "JFrog Security Demo App Builder" ${{ github.run_number }}
          jf rt build-publish "JFrog Security Demo App Builder" ${{ github.run_number }}
          
      # - name: Run JFrog Docker scan
      #   run: |
      #     docker images
      #     jf docker scan productdemo.jfrog.io/gartner-docker/jfrog/npm-demo:${{ github.run_number }}

      - name: Run JFrog Docker scan
        run: |
          jf build-scan "JFrog Security Demo App Builder" ${{ github.run_number }} --fail
